# version: "3.8"
services:
  backend:
    build: ./backend
    container_name: pong_backend
    environment:
      - DJANGO_SETTINGS_MODULE=${DJANGO_SETTINGS_MODULE}
      - DEBUG=${DEBUG}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=db
      - DB_PORT=${DB_PORT}
    restart: unless-stopped
    depends_on:
      - db
    networks:
      - pongnet
    expose:
      - "3000"
    ports:
      - "3000:3000"

  frontend-dev:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: pong_frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - pongnet
    environment:
      - VITE_BACKEND_URL=${VITE_BACKEND_URL}

  db:
    container_name: pong_db
    image: postgres:17-alpine
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - pongnet


  nginx:
    image: nginx:stable-alpine
    container_name: pong_nginx
    depends_on:
    - backend
    ports:
    - "8080:80"
    volumes:
    - ./frontend/dist:/usr/share/nginx/html:ro
    - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
    - pongnet

networks:
  pongnet:
    driver: bridge

volumes:
  db_data: