# Generated by Django 5.2.12 on 2026-03-26 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentgame',
            name='first_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
