# Generated by Django 5.2.12 on 2026-03-26 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0002_tournamentgame_first_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournamentgame',
            name='first_created_at',
        ),
    ]
