# Generated by Django 5.2.12 on 2026-03-07 23:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Achievement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                (
                    "requirement_type",
                    models.CharField(
                        choices=[
                            ("total_wins", "Total Wins"),
                            ("total_games", "Total Games"),
                            ("win_streak", "Win Streak"),
                            ("elo_rating", "ELO Rating"),
                        ],
                        max_length=20,
                    ),
                ),
                ("requirement_value", models.IntegerField()),
            ],
            options={
                "db_table": "stats_achievements",
                "ordering": ["requirement_value", "requirement_type", "name"],
            },
        ),
        migrations.CreateModel(
            name="Player",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_games", models.IntegerField(default=0)),
                ("total_wins", models.IntegerField(default=0)),
                ("total_losses", models.IntegerField(default=0)),
                ("elo_rating", models.IntegerField(default=1000)),
                ("total_win_points", models.IntegerField(default=0)),
                ("total_loss_points", models.IntegerField(default=0)),
                ("current_win_streak", models.IntegerField(default=0)),
                ("current_loss_streak", models.IntegerField(default=0)),
                ("best_win_streak", models.IntegerField(default=0)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "stats_players",
                "ordering": ["-elo_rating", "-total_wins"],
            },
        ),
        migrations.CreateModel(
            name="Match",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("player1_score", models.IntegerField()),
                ("player2_score", models.IntegerField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "loser",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="matches_lost",
                        to="game.player",
                    ),
                ),
                (
                    "player1",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matches_as_player1",
                        to="game.player",
                    ),
                ),
                (
                    "player2",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matches_as_player2",
                        to="game.player",
                    ),
                ),
                (
                    "winner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="matches_won",
                        to="game.player",
                    ),
                ),
            ],
            options={
                "db_table": "stats_matches",
            },
        ),
        migrations.CreateModel(
            name="PlayerAchievement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "achievement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="players",
                        to="game.achievement",
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="achievements",
                        to="game.player",
                    ),
                ),
            ],
            options={
                "db_table": "stats_player_achievements",
                "ordering": ["-timestamp"],
                "unique_together": {("player", "achievement")},
            },
        ),
    ]
