# Generated by Django 5.2.13 on 2026-04-16 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='achievement',
            options={'ordering': ['requirement_type', 'requirement_value', 'name', 'description']},
        ),
    ]
