# Generated by Django 5.2.13 on 2026-04-19 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_alter_achievement_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerachievement',
            name='match',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='earned_achievements', to='game.match'),
        ),
    ]
